openapi: 3.0.1

info:
  title: Alpha API Documentation
  description: Alpha Project
  version: 0.1.0
  
servers:
- url: http://localhost:3001/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Login & Get Token for Authorization
      security:
        - bearerAuth: [] 
      requestBody:
        description: Pet object that needs to be added to the store
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "superadmin"
                password:
                  type: string
                  example: superadmin
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    format: int64
                    example: 200
                  message:
                    type: string
                    example: User superadmin login.
                  userId:
                    type: string
                    example: d423b106-806d-44d6-8a6b-eb07ab9629a5
                  username:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNDIzYjEwNi04MDZkLTQ0ZDYtOGE2Yi1lYjA3YWI5NjI5YTUiLCJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE2MTExMzIzNTAsImV4cCI6MTYxMTEzOTU1MH0.jo6jX3cJJxDuZgCVzhdvlbfvC75az4RMa1CF8gvlIYs
  /auth/signup:
    post:
      tags:
        - auth
      summary: Sign up
      security:
        - bearerAuth: [] 
      requestBody:
        description: Pet object that needs to be added to the store
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "New Gamer 1234"
                email:
                  type: string
                  example: "newgamer1234@domain.com"
                username:
                  type: string
                  example: "newgamer1234"
                password:
                  type: string
                  example: passnewgamer1234
      responses:
        200:
          description: success
  /auth/logout/:id:
    delete:
      tags:
        - auth
      summary: Sign up
      security:
        - bearerAuth: [] 
      responses:
        200:
          description: success
